<?php

/**
 * Featured tournament catalog — single source of truth for the /tournaments page.
 */
return [
    [
        'id' => 'snake-championship',
        'emoji' => '🐍',
        'name' => 'Snake Championship',
        'game' => 'Snake',
        'backend_game' => 'snake',
        'category' => 'Arcade',
        'difficulty' => 'Medium',
        'players_current' => 2048,
        'players_max' => 4096,
        'prize' => '$5,000',
        'tag_label' => 'LIVE',
        'is_live' => true,
        'time_left' => '2h 14m',
        'cover_image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=75',
        'accent' => '#ccff00',
        'secondary' => '#10b981',
        'sort_order' => 1,
    ],
    [
        'id' => 'tictactoe-masters',
        'emoji' => '❌',
        'name' => 'Tic Tac Toe Masters',
        'game' => 'Tic Tac Toe',
        'backend_game' => 'tic_tac_toe',
        'category' => 'Strategy',
        'difficulty' => 'Easy',
        'players_current' => 512,
        'players_max' => 512,
        'prize' => '$2,000',
        'tag_label' => 'FINALS',
        'is_live' => false,
        'time_left' => '48m',
        'cover_image' => 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&w=800&q=75',
        'accent' => '#f97316',
        'secondary' => '#ef4444',
        'sort_order' => 2,
    ],
    [
        'id' => 'memory-grand-prix',
        'emoji' => '🧠',
        'name' => 'Memory Grand Prix',
        'game' => 'Memory Match',
        'backend_game' => 'memory',
        'category' => 'Puzzle',
        'difficulty' => 'Medium',
        'players_current' => 800,
        'players_max' => 1024,
        'prize' => '$4,200',
        'tag_label' => 'LIVE',
        'is_live' => true,
        'time_left' => '1h 30m',
        'cover_image' => 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=800&q=75',
        'accent' => '#a78bfa',
        'secondary' => '#7c3aed',
        'sort_order' => 3,
    ],
    [
        'id' => 'number-guessing-open',
        'emoji' => '🔢',
        'name' => 'Number Guessing Open',
        'game' => 'Number Guessing',
        'backend_game' => 'number',
        'category' => 'Puzzle',
        'difficulty' => 'Easy',
        'players_current' => 640,
        'players_max' => 1000,
        'prize' => '$1,500',
        'tag_label' => 'OPEN',
        'is_live' => false,
        'time_left' => 'Starts in 2d',
        'cover_image' => 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=800&q=75',
        'accent' => '#facc15',
        'secondary' => '#f59e0b',
        'sort_order' => 4,
    ],
    [
        'id' => 'pixel-memory-ultra',
        'emoji' => '🧩',
        'name' => 'Pixel Memory Ultra',
        'game' => 'Memory Match',
        'backend_game' => 'memory',
        'category' => 'Puzzle',
        'difficulty' => 'Medium',
        'players_current' => 900,
        'players_max' => 2000,
        'prize' => '$6,000',
        'tag_label' => 'REGISTERING',
        'is_live' => false,
        'time_left' => 'Starts in 5h',
        'cover_image' => 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=75',
        'accent' => '#00ffff',
        'secondary' => '#ff00ff',
        'sort_order' => 5,
    ],
    [
        'id' => 'chess-blitz-open',
        'emoji' => '♟️',
        'name' => 'Chess Blitz Open',
        'game' => 'Chess Blitz',
        'backend_game' => 'chess',
        'category' => 'Strategy',
        'difficulty' => 'Hard',
        'players_current' => 2000,
        'players_max' => 2048,
        'prize' => '$10,000',
        'tag_label' => 'FINALS',
        'is_live' => false,
        'time_left' => '30m',
        'cover_image' => 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=800&q=75',
        'accent' => '#60a5fa',
        'secondary' => '#6366f1',
        'sort_order' => 6,
    ],
];
